name: "Deploy status"
on:
  push:
    branches:
      - master
      - dev
jobs:
  deploy-blog:
    name: Deploying the static pages to the FTP server
    runs-on: ubuntu-latest
    container: klakegg/hugo:ext-ubuntu
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Check Hugo version
        run: hugo version
      - name: Build static pages
        run: hugo
      - name: Deploy static pages
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_URL }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "CodeIT/exampleSite/public"
          remoteDir: "www/codeit.suntprogramator.dev"
